/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_account</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_account.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmAccountDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>user_id</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>account_id</tt>.
	 */
	private String accountId;

	/**
	 * This property corresponds to db column <tt>account_name</tt>.
	 */
	private String accountName;

	/**
	 * This property corresponds to db column <tt>account_type</tt>.
	 */
	private String accountType;

	/**
	 * This property corresponds to db column <tt>sub_account_type</tt>.
	 */
	private String subAccountType;

	/**
	 * This property corresponds to db column <tt>balance</tt>.
	 */
	private BigDecimal balance;

	/**
	 * This property corresponds to db column <tt>currency</tt>.
	 */
	private String currency;

	/**
	 * This property corresponds to db column <tt>direction</tt>.
	 */
	private String direction;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>accountId</tt>.
     *
     * @return property value of accountId
     */
	public String getAccountId() {
		return accountId;
	}
	
	/**
	 * Setter method for property <tt>accountId</tt>.
	 * 
	 * @param accountId value to be assigned to property accountId
     */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

    /**
     * Getter method for property <tt>accountName</tt>.
     *
     * @return property value of accountName
     */
	public String getAccountName() {
		return accountName;
	}
	
	/**
	 * Setter method for property <tt>accountName</tt>.
	 * 
	 * @param accountName value to be assigned to property accountName
     */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

    /**
     * Getter method for property <tt>accountType</tt>.
     *
     * @return property value of accountType
     */
	public String getAccountType() {
		return accountType;
	}
	
	/**
	 * Setter method for property <tt>accountType</tt>.
	 * 
	 * @param accountType value to be assigned to property accountType
     */
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

    /**
     * Getter method for property <tt>subAccountType</tt>.
     *
     * @return property value of subAccountType
     */
	public String getSubAccountType() {
		return subAccountType;
	}
	
	/**
	 * Setter method for property <tt>subAccountType</tt>.
	 * 
	 * @param subAccountType value to be assigned to property subAccountType
     */
	public void setSubAccountType(String subAccountType) {
		this.subAccountType = subAccountType;
	}

    /**
     * Getter method for property <tt>balance</tt>.
     *
     * @return property value of balance
     */
	public BigDecimal getBalance() {
		return balance;
	}
	
	/**
	 * Setter method for property <tt>balance</tt>.
	 * 
	 * @param balance value to be assigned to property balance
     */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

    /**
     * Getter method for property <tt>currency</tt>.
     *
     * @return property value of currency
     */
	public String getCurrency() {
		return currency;
	}
	
	/**
	 * Setter method for property <tt>currency</tt>.
	 * 
	 * @param currency value to be assigned to property currency
     */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

    /**
     * Getter method for property <tt>direction</tt>.
     *
     * @return property value of direction
     */
	public String getDirection() {
		return direction;
	}
	
	/**
	 * Setter method for property <tt>direction</tt>.
	 * 
	 * @param direction value to be assigned to property direction
     */
	public void setDirection(String direction) {
		this.direction = direction;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
