/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.util.Date;
import java.math.BigDecimal;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_account_log</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_account_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmAccountLogDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>trans_log_id</tt>.
	 */
	private String transLogId;

	/**
	 * This property corresponds to db column <tt>direction</tt>.
	 */
	private String direction;

	/**
	 * This property corresponds to db column <tt>account</tt>.
	 */
	private String account;

	/**
	 * This property corresponds to db column <tt>trans_amt</tt>.
	 */
	private BigDecimal transAmt;

	/**
	 * This property corresponds to db column <tt>balance</tt>.
	 */
	private BigDecimal balance;

	/**
	 * This property corresponds to db column <tt>memo</tt>.
	 */
	private String memo;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>transLogId</tt>.
     *
     * @return property value of transLogId
     */
	public String getTransLogId() {
		return transLogId;
	}
	
	/**
	 * Setter method for property <tt>transLogId</tt>.
	 * 
	 * @param transLogId value to be assigned to property transLogId
     */
	public void setTransLogId(String transLogId) {
		this.transLogId = transLogId;
	}

    /**
     * Getter method for property <tt>direction</tt>.
     *
     * @return property value of direction
     */
	public String getDirection() {
		return direction;
	}
	
	/**
	 * Setter method for property <tt>direction</tt>.
	 * 
	 * @param direction value to be assigned to property direction
     */
	public void setDirection(String direction) {
		this.direction = direction;
	}

    /**
     * Getter method for property <tt>account</tt>.
     *
     * @return property value of account
     */
	public String getAccount() {
		return account;
	}
	
	/**
	 * Setter method for property <tt>account</tt>.
	 * 
	 * @param account value to be assigned to property account
     */
	public void setAccount(String account) {
		this.account = account;
	}

    /**
     * Getter method for property <tt>transAmt</tt>.
     *
     * @return property value of transAmt
     */
	public BigDecimal getTransAmt() {
		return transAmt;
	}
	
	/**
	 * Setter method for property <tt>transAmt</tt>.
	 * 
	 * @param transAmt value to be assigned to property transAmt
     */
	public void setTransAmt(BigDecimal transAmt) {
		this.transAmt = transAmt;
	}

    /**
     * Getter method for property <tt>balance</tt>.
     *
     * @return property value of balance
     */
	public BigDecimal getBalance() {
		return balance;
	}
	
	/**
	 * Setter method for property <tt>balance</tt>.
	 * 
	 * @param balance value to be assigned to property balance
     */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
