/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_invest_duein_rcd</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_invest_duein_rcd.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmInvestDueinRcdDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>invest_record_id</tt>.
	 */
	private String investRecordId;

	/**
	 * This property corresponds to db column <tt>period_index</tt>.
	 */
	private int periodIndex;

	/**
	 * This property corresponds to db column <tt>repay_amt</tt>.
	 */
	private BigDecimal repayAmt;

	/**
	 * This property corresponds to db column <tt>repay_interest_amt</tt>.
	 */
	private BigDecimal repayInterestAmt;

	/**
	 * This property corresponds to db column <tt>repay_date</tt>.
	 */
	private String repayDate;

	/**
	 * This property corresponds to db column <tt>actual_repay_date</tt>.
	 */
	private String actualRepayDate;

	/**
	 * This property corresponds to db column <tt>is_delay</tt>.
	 */
	private String isDelay;

	/**
	 * This property corresponds to db column <tt>is_finish</tt>.
	 */
	private String isFinish;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>investRecordId</tt>.
     *
     * @return property value of investRecordId
     */
	public String getInvestRecordId() {
		return investRecordId;
	}
	
	/**
	 * Setter method for property <tt>investRecordId</tt>.
	 * 
	 * @param investRecordId value to be assigned to property investRecordId
     */
	public void setInvestRecordId(String investRecordId) {
		this.investRecordId = investRecordId;
	}

    /**
     * Getter method for property <tt>periodIndex</tt>.
     *
     * @return property value of periodIndex
     */
	public int getPeriodIndex() {
		return periodIndex;
	}
	
	/**
	 * Setter method for property <tt>periodIndex</tt>.
	 * 
	 * @param periodIndex value to be assigned to property periodIndex
     */
	public void setPeriodIndex(int periodIndex) {
		this.periodIndex = periodIndex;
	}

    /**
     * Getter method for property <tt>repayAmt</tt>.
     *
     * @return property value of repayAmt
     */
	public BigDecimal getRepayAmt() {
		return repayAmt;
	}
	
	/**
	 * Setter method for property <tt>repayAmt</tt>.
	 * 
	 * @param repayAmt value to be assigned to property repayAmt
     */
	public void setRepayAmt(BigDecimal repayAmt) {
		this.repayAmt = repayAmt;
	}

    /**
     * Getter method for property <tt>repayInterestAmt</tt>.
     *
     * @return property value of repayInterestAmt
     */
	public BigDecimal getRepayInterestAmt() {
		return repayInterestAmt;
	}
	
	/**
	 * Setter method for property <tt>repayInterestAmt</tt>.
	 * 
	 * @param repayInterestAmt value to be assigned to property repayInterestAmt
     */
	public void setRepayInterestAmt(BigDecimal repayInterestAmt) {
		this.repayInterestAmt = repayInterestAmt;
	}

    /**
     * Getter method for property <tt>repayDate</tt>.
     *
     * @return property value of repayDate
     */
	public String getRepayDate() {
		return repayDate;
	}
	
	/**
	 * Setter method for property <tt>repayDate</tt>.
	 * 
	 * @param repayDate value to be assigned to property repayDate
     */
	public void setRepayDate(String repayDate) {
		this.repayDate = repayDate;
	}

    /**
     * Getter method for property <tt>actualRepayDate</tt>.
     *
     * @return property value of actualRepayDate
     */
	public String getActualRepayDate() {
		return actualRepayDate;
	}
	
	/**
	 * Setter method for property <tt>actualRepayDate</tt>.
	 * 
	 * @param actualRepayDate value to be assigned to property actualRepayDate
     */
	public void setActualRepayDate(String actualRepayDate) {
		this.actualRepayDate = actualRepayDate;
	}

    /**
     * Getter method for property <tt>isDelay</tt>.
     *
     * @return property value of isDelay
     */
	public String getIsDelay() {
		return isDelay;
	}
	
	/**
	 * Setter method for property <tt>isDelay</tt>.
	 * 
	 * @param isDelay value to be assigned to property isDelay
     */
	public void setIsDelay(String isDelay) {
		this.isDelay = isDelay;
	}

    /**
     * Getter method for property <tt>isFinish</tt>.
     *
     * @return property value of isFinish
     */
	public String getIsFinish() {
		return isFinish;
	}
	
	/**
	 * Setter method for property <tt>isFinish</tt>.
	 * 
	 * @param isFinish value to be assigned to property isFinish
     */
	public void setIsFinish(String isFinish) {
		this.isFinish = isFinish;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
