/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.util.Date;
import java.math.BigDecimal;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_invest_rcd</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_invest_rcd.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmInvestRcdDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>platform_user_id</tt>.
	 */
	private String platformUserId;

	/**
	 * This property corresponds to db column <tt>period</tt>.
	 */
	private int period;

	/**
	 * This property corresponds to db column <tt>period_type</tt>.
	 */
	private String periodType;

	/**
	 * This property corresponds to db column <tt>repay_method</tt>.
	 */
	private String repayMethod;

	/**
	 * This property corresponds to db column <tt>invest_amt</tt>.
	 */
	private BigDecimal investAmt;

	/**
	 * This property corresponds to db column <tt>invest_date</tt>.
	 */
	private String investDate;

	/**
	 * This property corresponds to db column <tt>interest_rate_type</tt>.
	 */
	private String interestRateType;

	/**
	 * This property corresponds to db column <tt>interest_rate</tt>.
	 */
	private BigDecimal interestRate;

	/**
	 * This property corresponds to db column <tt>interest_amt</tt>.
	 */
	private BigDecimal interestAmt;

	/**
	 * This property corresponds to db column <tt>cost_amt</tt>.
	 */
	private BigDecimal costAmt;

	/**
	 * This property corresponds to db column <tt>price_amt</tt>.
	 */
	private BigDecimal priceAmt;

	/**
	 * This property corresponds to db column <tt>fee_rate</tt>.
	 */
	private BigDecimal feeRate;

	/**
	 * This property corresponds to db column <tt>is_finish</tt>.
	 */
	private String isFinish;

	/**
	 * This property corresponds to db column <tt>memo</tt>.
	 */
	private String memo;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>platformUserId</tt>.
     *
     * @return property value of platformUserId
     */
	public String getPlatformUserId() {
		return platformUserId;
	}
	
	/**
	 * Setter method for property <tt>platformUserId</tt>.
	 * 
	 * @param platformUserId value to be assigned to property platformUserId
     */
	public void setPlatformUserId(String platformUserId) {
		this.platformUserId = platformUserId;
	}

    /**
     * Getter method for property <tt>period</tt>.
     *
     * @return property value of period
     */
	public int getPeriod() {
		return period;
	}
	
	/**
	 * Setter method for property <tt>period</tt>.
	 * 
	 * @param period value to be assigned to property period
     */
	public void setPeriod(int period) {
		this.period = period;
	}

    /**
     * Getter method for property <tt>periodType</tt>.
     *
     * @return property value of periodType
     */
	public String getPeriodType() {
		return periodType;
	}
	
	/**
	 * Setter method for property <tt>periodType</tt>.
	 * 
	 * @param periodType value to be assigned to property periodType
     */
	public void setPeriodType(String periodType) {
		this.periodType = periodType;
	}

    /**
     * Getter method for property <tt>repayMethod</tt>.
     *
     * @return property value of repayMethod
     */
	public String getRepayMethod() {
		return repayMethod;
	}
	
	/**
	 * Setter method for property <tt>repayMethod</tt>.
	 * 
	 * @param repayMethod value to be assigned to property repayMethod
     */
	public void setRepayMethod(String repayMethod) {
		this.repayMethod = repayMethod;
	}

    /**
     * Getter method for property <tt>investAmt</tt>.
     *
     * @return property value of investAmt
     */
	public BigDecimal getInvestAmt() {
		return investAmt;
	}
	
	/**
	 * Setter method for property <tt>investAmt</tt>.
	 * 
	 * @param investAmt value to be assigned to property investAmt
     */
	public void setInvestAmt(BigDecimal investAmt) {
		this.investAmt = investAmt;
	}

    /**
     * Getter method for property <tt>investDate</tt>.
     *
     * @return property value of investDate
     */
	public String getInvestDate() {
		return investDate;
	}
	
	/**
	 * Setter method for property <tt>investDate</tt>.
	 * 
	 * @param investDate value to be assigned to property investDate
     */
	public void setInvestDate(String investDate) {
		this.investDate = investDate;
	}

    /**
     * Getter method for property <tt>interestRateType</tt>.
     *
     * @return property value of interestRateType
     */
	public String getInterestRateType() {
		return interestRateType;
	}
	
	/**
	 * Setter method for property <tt>interestRateType</tt>.
	 * 
	 * @param interestRateType value to be assigned to property interestRateType
     */
	public void setInterestRateType(String interestRateType) {
		this.interestRateType = interestRateType;
	}

    /**
     * Getter method for property <tt>interestRate</tt>.
     *
     * @return property value of interestRate
     */
	public BigDecimal getInterestRate() {
		return interestRate;
	}
	
	/**
	 * Setter method for property <tt>interestRate</tt>.
	 * 
	 * @param interestRate value to be assigned to property interestRate
     */
	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

    /**
     * Getter method for property <tt>interestAmt</tt>.
     *
     * @return property value of interestAmt
     */
	public BigDecimal getInterestAmt() {
		return interestAmt;
	}
	
	/**
	 * Setter method for property <tt>interestAmt</tt>.
	 * 
	 * @param interestAmt value to be assigned to property interestAmt
     */
	public void setInterestAmt(BigDecimal interestAmt) {
		this.interestAmt = interestAmt;
	}

    /**
     * Getter method for property <tt>costAmt</tt>.
     *
     * @return property value of costAmt
     */
	public BigDecimal getCostAmt() {
		return costAmt;
	}
	
	/**
	 * Setter method for property <tt>costAmt</tt>.
	 * 
	 * @param costAmt value to be assigned to property costAmt
     */
	public void setCostAmt(BigDecimal costAmt) {
		this.costAmt = costAmt;
	}

    /**
     * Getter method for property <tt>priceAmt</tt>.
     *
     * @return property value of priceAmt
     */
	public BigDecimal getPriceAmt() {
		return priceAmt;
	}
	
	/**
	 * Setter method for property <tt>priceAmt</tt>.
	 * 
	 * @param priceAmt value to be assigned to property priceAmt
     */
	public void setPriceAmt(BigDecimal priceAmt) {
		this.priceAmt = priceAmt;
	}

    /**
     * Getter method for property <tt>feeRate</tt>.
     *
     * @return property value of feeRate
     */
	public BigDecimal getFeeRate() {
		return feeRate;
	}
	
	/**
	 * Setter method for property <tt>feeRate</tt>.
	 * 
	 * @param feeRate value to be assigned to property feeRate
     */
	public void setFeeRate(BigDecimal feeRate) {
		this.feeRate = feeRate;
	}

    /**
     * Getter method for property <tt>isFinish</tt>.
     *
     * @return property value of isFinish
     */
	public String getIsFinish() {
		return isFinish;
	}
	
	/**
	 * Setter method for property <tt>isFinish</tt>.
	 * 
	 * @param isFinish value to be assigned to property isFinish
     */
	public void setIsFinish(String isFinish) {
		this.isFinish = isFinish;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
