/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_invest_from_account</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_invest_from_account.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmInvestFromAccountDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>invest_record_id</tt>.
	 */
	private String investRecordId;

	/**
	 * This property corresponds to db column <tt>account_id</tt>.
	 */
	private String accountId;

	/**
	 * This property corresponds to db column <tt>amount</tt>.
	 */
	private BigDecimal amount;

	/**
	 * This property corresponds to db column <tt>currency</tt>.
	 */
	private String currency;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>investRecordId</tt>.
     *
     * @return property value of investRecordId
     */
	public String getInvestRecordId() {
		return investRecordId;
	}
	
	/**
	 * Setter method for property <tt>investRecordId</tt>.
	 * 
	 * @param investRecordId value to be assigned to property investRecordId
     */
	public void setInvestRecordId(String investRecordId) {
		this.investRecordId = investRecordId;
	}

    /**
     * Getter method for property <tt>accountId</tt>.
     *
     * @return property value of accountId
     */
	public String getAccountId() {
		return accountId;
	}
	
	/**
	 * Setter method for property <tt>accountId</tt>.
	 * 
	 * @param accountId value to be assigned to property accountId
     */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

    /**
     * Getter method for property <tt>amount</tt>.
     *
     * @return property value of amount
     */
	public BigDecimal getAmount() {
		return amount;
	}
	
	/**
	 * Setter method for property <tt>amount</tt>.
	 * 
	 * @param amount value to be assigned to property amount
     */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

    /**
     * Getter method for property <tt>currency</tt>.
     *
     * @return property value of currency
     */
	public String getCurrency() {
		return currency;
	}
	
	/**
	 * Setter method for property <tt>currency</tt>.
	 * 
	 * @param currency value to be assigned to property currency
     */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
