/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import java.util.Date;
import java.math.BigDecimal;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>dnm_platform_user</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_platform_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DnmPlatformUserDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>user_id</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>platform_id</tt>.
	 */
	private String platformId;

	/**
	 * This property corresponds to db column <tt>platform_user_id</tt>.
	 */
	private String platformUserId;

	/**
	 * This property corresponds to db column <tt>total_invest_amt</tt>.
	 */
	private BigDecimal totalInvestAmt;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>platformId</tt>.
     *
     * @return property value of platformId
     */
	public String getPlatformId() {
		return platformId;
	}
	
	/**
	 * Setter method for property <tt>platformId</tt>.
	 * 
	 * @param platformId value to be assigned to property platformId
     */
	public void setPlatformId(String platformId) {
		this.platformId = platformId;
	}

    /**
     * Getter method for property <tt>platformUserId</tt>.
     *
     * @return property value of platformUserId
     */
	public String getPlatformUserId() {
		return platformUserId;
	}
	
	/**
	 * Setter method for property <tt>platformUserId</tt>.
	 * 
	 * @param platformUserId value to be assigned to property platformUserId
     */
	public void setPlatformUserId(String platformUserId) {
		this.platformUserId = platformUserId;
	}

    /**
     * Getter method for property <tt>totalInvestAmt</tt>.
     *
     * @return property value of totalInvestAmt
     */
	public BigDecimal getTotalInvestAmt() {
		return totalInvestAmt;
	}
	
	/**
	 * Setter method for property <tt>totalInvestAmt</tt>.
	 * 
	 * @param totalInvestAmt value to be assigned to property totalInvestAmt
     */
	public void setTotalInvestAmt(BigDecimal totalInvestAmt) {
		this.totalInvestAmt = totalInvestAmt;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
