/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.dataobject;

// auto generated imports
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>sequence</tt>.
 *
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sequence.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class SequenceDO {

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>name</tt>.
	 */
	private String name;

	/**
	 * This property corresponds to db column <tt>current_value</tt>.
	 */
	private int currentValue;

	/**
	 * This property corresponds to db column <tt>min_value</tt>.
	 */
	private int minValue;

	/**
	 * This property corresponds to db column <tt>max_value</tt>.
	 */
	private int maxValue;

	/**
	 * This property corresponds to db column <tt>increment</tt>.
	 */
	private int increment;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>name</tt>.
     *
     * @return property value of name
     */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter method for property <tt>name</tt>.
	 * 
	 * @param name value to be assigned to property name
     */
	public void setName(String name) {
		this.name = name;
	}

    /**
     * Getter method for property <tt>currentValue</tt>.
     *
     * @return property value of currentValue
     */
	public int getCurrentValue() {
		return currentValue;
	}
	
	/**
	 * Setter method for property <tt>currentValue</tt>.
	 * 
	 * @param currentValue value to be assigned to property currentValue
     */
	public void setCurrentValue(int currentValue) {
		this.currentValue = currentValue;
	}

    /**
     * Getter method for property <tt>minValue</tt>.
     *
     * @return property value of minValue
     */
	public int getMinValue() {
		return minValue;
	}
	
	/**
	 * Setter method for property <tt>minValue</tt>.
	 * 
	 * @param minValue value to be assigned to property minValue
     */
	public void setMinValue(int minValue) {
		this.minValue = minValue;
	}

    /**
     * Getter method for property <tt>maxValue</tt>.
     *
     * @return property value of maxValue
     */
	public int getMaxValue() {
		return maxValue;
	}
	
	/**
	 * Setter method for property <tt>maxValue</tt>.
	 * 
	 * @param maxValue value to be assigned to property maxValue
     */
	public void setMaxValue(int maxValue) {
		this.maxValue = maxValue;
	}

    /**
     * Getter method for property <tt>increment</tt>.
     *
     * @return property value of increment
     */
	public int getIncrement() {
		return increment;
	}
	
	/**
	 * Setter method for property <tt>increment</tt>.
	 * 
	 * @param increment value to be assigned to property increment
     */
	public void setIncrement(int increment) {
		this.increment = increment;
	}

	@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
