/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.ibatis;import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;import com.dnm.core.common.dal.daointerface.DnmAccountTransLogDAO;// auto generated importsimport com.dnm.core.common.dal.dataobject.DnmAccountTransLogDO;import org.springframework.dao.DataAccessException;/** * An ibatis based implementation of dao interface <tt>com.dnm.core.common.dal.daointerface.DnmAccountTransLogDAO</tt>. * * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_account_trans_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */public class IbatisDnmAccountTransLogDAO extends SqlMapClientDaoSupport implements DnmAccountTransLogDAO {	/**
	 *  Insert one <tt>DnmAccountTransLogDO</tt> object to DB table <tt>dnm_account_trans_log</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into dnm_account_trans_log(id,user_id,guid,biz_id,trans_code,trans_sub_code,trans_amt,trans_currency,trans_time,debit_account,credit_account,memo,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param dnmAccountTransLog
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(DnmAccountTransLogDO dnmAccountTransLog) throws DataAccessException {
    	if (dnmAccountTransLog == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-DNM-ACCOUNT-TRANS-LOG-INSERT", dnmAccountTransLog);

        return dnmAccountTransLog.getId();
    }		/**
	 *  Query DB table <tt>dnm_account_trans_log</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, guid, biz_id, trans_code, trans_sub_code, trans_amt, trans_currency, trans_time, debit_account, credit_account, memo, gmt_create, gmt_modified from dnm_account_trans_log where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return DnmAccountTransLogDO
	 *	@throws DataAccessException
	 */	 
    public DnmAccountTransLogDO load(String id) throws DataAccessException {

        return (DnmAccountTransLogDO) getSqlMapClientTemplate().queryForObject("MS-DNM-ACCOUNT-TRANS-LOG-LOAD", id);

    }	}	