/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.dnm.core.common.dal.ibatis;import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;import com.dnm.core.common.dal.daointerface.DnmUserDAO;// auto generated importsimport com.dnm.core.common.dal.dataobject.DnmUserDO;import org.springframework.dao.DataAccessException;import java.util.Map;import java.util.HashMap;/** * An ibatis based implementation of dao interface <tt>com.dnm.core.common.dal.daointerface.DnmUserDAO</tt>. * * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dnm_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */public class IbatisDnmUserDAO extends SqlMapClientDaoSupport implements DnmUserDAO {	/**
	 *  Insert one <tt>DnmUserDO</tt> object to DB table <tt>dnm_user</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into dnm_user(id,username,password,email,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param dnmUser
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(DnmUserDO dnmUser) throws DataAccessException {
    	if (dnmUser == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-DNM-USER-INSERT", dnmUser);

        return dnmUser.getId();
    }		/**
	 *  Query DB table <tt>dnm_user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, username, password, email, gmt_create, gmt_modified from dnm_user where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return DnmUserDO
	 *	@throws DataAccessException
	 */	 
    public DnmUserDO load(String id) throws DataAccessException {

        return (DnmUserDO) getSqlMapClientTemplate().queryForObject("MS-DNM-USER-LOAD", id);

    }		/**
	 *  Query DB table <tt>dnm_user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, username, password, email, gmt_create, gmt_modified from dnm_user where ((username = ?) AND (password = ?))</tt>
	 *
	 *	@param username
	 *	@param password
	 *	@return DnmUserDO
	 *	@throws DataAccessException
	 */	 
    public DnmUserDO loadByUsernameAndPwd(String username, String password) throws DataAccessException {
        Map param = new HashMap();

        param.put("username", username);
        param.put("password", password);

        return (DnmUserDO) getSqlMapClientTemplate().queryForObject("MS-DNM-USER-LOAD-BY-USERNAME-AND-PWD", param);

    }	}	